/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package karaanbank;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hp
 */
public class checkbalance extends javax.swing.JInternalFrame {
    Connection con = null;
    PreparedStatement st = null;
    public void db_con() {
        String url = "jdbc:mysql://localhost:3306/kaaraanbank";
        String user = "root";
        String pass = "";

        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection(url, user, pass);
//            JOptionPane.showMessageDialog(null,"connected successfully");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public checkbalance() {
        initComponents();
        Date d = new Date();
        db_con();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        account_txt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        type_combo = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        show_tbl = new javax.swing.JTable();
        total_credit_lbl = new javax.swing.JLabel();
        total_debit_lbl = new javax.swing.JLabel();
        current_balance_lbl = new javax.swing.JLabel();

        setBackground(new java.awt.Color(102, 102, 0));
        setClosable(true);
        setTitle("Check Balance");

        jPanel1.setBackground(new java.awt.Color(102, 102, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Check Balance", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24)), "Check Balance", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 24), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Enter AccountNO:");

        account_txt.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        account_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                account_txtKeyReleased(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Transaction type:");

        type_combo.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        type_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Credit", "Debit" }));
        type_combo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                type_comboItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(account_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(103, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(account_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        show_tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Transaction ID", "AccountNO", "Holder", "Credit", "Debit", "Transactedby", "describtion", "Date"
            }
        ));
        jScrollPane1.setViewportView(show_tbl);

        total_credit_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_credit_lbl.setForeground(new java.awt.Color(255, 255, 255));
        total_credit_lbl.setText("Total Credit: 0.00");

        total_debit_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        total_debit_lbl.setForeground(new java.awt.Color(255, 255, 255));
        total_debit_lbl.setText("Total Debit:  0.00");

        current_balance_lbl.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        current_balance_lbl.setForeground(new java.awt.Color(255, 255, 255));
        current_balance_lbl.setText("Current Balance:  0.00");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(current_balance_lbl)
                    .addComponent(total_debit_lbl)
                    .addComponent(total_credit_lbl))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(total_credit_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(total_debit_lbl)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(current_balance_lbl)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void account_txtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_account_txtKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tbl=(DefaultTableModel) show_tbl.getModel();
        tbl.setRowCount(0);
         try {
             double credit=0;        
             double debit=0;
             st = con.prepareStatement("select t.*,o.holder from transaction t INNER JOIN open_account o ON t.account=o.account where t.account='" + account_txt.getText() + "'");
             ResultSet r = st.executeQuery();
             while (r.next()) {
                 credit+=r.getDouble("credit"); 
                 debit+=r.getDouble("debit");
                 tbl.addRow(new Object[]{
                     r.getString("tid"), 
                     r.getString("account"),
                     r.getString("holder"),
                     r.getString("credit"),
                     r.getString("debit"),
                     r.getString("depositedby"),
                     r.getString("describtion"),      
                     r.getString("date")
                 });
            }   
             tbl.addRow(new Object[]{null,null,null,credit,debit,null,null,null});
         total_credit_lbl.setText("total credit: $"+credit+"USD");    
         total_debit_lbl.setText("total debit: $"+debit+"USD");   
         current_balance_lbl.setText("current balance: $"+(credit-debit)+"USD");

         } catch (Exception error) {
            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_account_txtKeyReleased

    private void type_comboItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_type_comboItemStateChanged
        // TODO add your handling code here:
        String type=type_combo.getSelectedItem().toString();
         DefaultTableModel tbl=(DefaultTableModel) show_tbl.getModel();
        tbl.setRowCount(0);
         try {
             double credit=0;        
             double debit=0;
             st = con.prepareStatement("select t.*,o.holder from transaction t INNER JOIN open_account o ON t.account=o.account where t.account='" + account_txt.getText() + "' and transaction_type='" + type+ "'");
             ResultSet r = st.executeQuery();
             while (r.next()) {
                 credit+=r.getDouble("credit"); 
                 debit+=r.getDouble("debit");
                 tbl.addRow(new Object[]{
                     r.getString("tid"), 
                     r.getString("account"),
                     r.getString("holder"),
                     r.getString("credit"),
                     r.getString("debit"),
                     r.getString("depositedby"),
                     r.getString("describtion"),      
                     r.getString("date")
                 });
            }   
             tbl.addRow(new Object[]{null,null,null,credit,debit,null,null,null});
         total_credit_lbl.setText("total credit: $"+credit+"USD");    
         total_debit_lbl.setText("total debit: $"+debit+"USD");   
         current_balance_lbl.setText("current balance: $"+(credit-debit)+"USD");

         } catch (Exception error) {
            JOptionPane.showMessageDialog(null, error);
        }
    }//GEN-LAST:event_type_comboItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_txt;
    private javax.swing.JLabel current_balance_lbl;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable show_tbl;
    private javax.swing.JLabel total_credit_lbl;
    private javax.swing.JLabel total_debit_lbl;
    private javax.swing.JComboBox type_combo;
    // End of variables declaration//GEN-END:variables
}
