/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package karaanbank;

import java.sql.*;

import java.sql.Connection;
import javax.swing.JOptionPane;
import java.util.Date;

/**
 *
 * @author hp
 */
public class open_account extends javax.swing.JInternalFrame {
    Connection con =null;
    PreparedStatement st=null;
    private Object JoptionPane;
    public void db_con(){
        String url="jdbc:mysql://localhost:3306/kaaraanbank";    
        String user="root";
        String pass="";

        try{
            Class.forName("com.mysql.jdbc.Driver");
            con=DriverManager.getConnection(url, user, pass);
//            JOptionPane.showMessageDialog(null,"connected successfully");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }
    public void Create_account(String account,String holder,String type,String id,String contact,String balance,
            String status , String open_date){
            try{
                st=con.prepareStatement("INSERT INTO open_account VALUES('"+account+"','"+holder+"','"+type+"','"+id+"','"+contact+"','"+balance+"','"+status+"','"+open_date+"')");
                int i=st.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null,"your account was successfully created");
            }
            else{
                JOptionPane.showMessageDialog(null,"could not create account due to some error");

            }
                }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
        }
    public open_account() {
        initComponents();
        db_con();
        clear_all_textboxes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField5 = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        contact_txt = new javax.swing.JTextField();
        account_txt = new javax.swing.JTextField();
        type_combo = new javax.swing.JComboBox();
        balance_txt = new javax.swing.JTextField();
        holder_txt = new javax.swing.JTextField();
        identity_txt = new javax.swing.JTextField();
        status_combo = new javax.swing.JComboBox();
        create = new javax.swing.JButton();
        update = new javax.swing.JButton();
        search = new javax.swing.JButton();
        close = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("open new bank account");

        jPanel1.setBackground(new java.awt.Color(153, 255, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("Account number: ");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Account Holder: ");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("Account Type: ");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("Account Holder ID: ");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Contact NO:");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("Account Balance: ");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("Account Status: ");

        contact_txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        account_txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        type_combo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        type_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Current Account", "Saving Account", "Loan Account" }));

        balance_txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        holder_txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        identity_txt.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N

        status_combo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        status_combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Open ", "Closed", " " }));

        create.setText("Create");
        create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createActionPerformed(evt);
            }
        });

        update.setText("Update");
        update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateActionPerformed(evt);
            }
        });

        search.setText("Search");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });

        close.setText("Close");
        close.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel7))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(create)
                        .addGap(28, 28, 28)
                        .addComponent(search)
                        .addGap(18, 18, 18)
                        .addComponent(update)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(close)
                        .addGap(130, 130, 130))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(status_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(balance_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(type_combo, javax.swing.GroupLayout.Alignment.LEADING, 0, 347, Short.MAX_VALUE)
                            .addComponent(holder_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(account_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(identity_txt, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contact_txt, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(account_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(holder_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(type_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(identity_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(contact_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(balance_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(status_combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(create)
                    .addComponent(update)
                    .addComponent(search)
                    .addComponent(close))
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 611, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createActionPerformed
        // TODO add your handling code here:
        Date d=new Date();
         try{
             Create_account(account_txt.getText(),
                     holder_txt.getText(),
                     type_combo.getSelectedItem().toString(),
                     identity_txt.getText(),
                     contact_txt.getText(),
                     balance_txt.getText(),
                     status_combo.getSelectedItem().toString(),
                     d.toLocaleString()
                     );
             clear_all_textboxes();
                }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_createActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
        // TODO add your handling code here:
        try{
           st=con.prepareStatement("select * from open_account where account='"+account_txt.getText()+"'");
           ResultSet rs=st.executeQuery();
           if(rs.next()){
               account_txt.setText(rs.getString(1));    
               holder_txt.setText(rs.getString(2));
               type_combo.setSelectedItem(rs.getString(3));
               identity_txt.setText(rs.getString(4));
               contact_txt.setText(rs.getString(5));
               balance_txt.setText(rs.getString(6));  
               status_combo.setSelectedItem(rs.getString(7));
//               make disable
//               account_txt.disable();    
//               holder_txt.disable(); 
//               type_combo.disable(); 
//               identity_txt.disable(); 
//               contact_txt.disable(); 
//               balance_txt.disable();   
//               status_combo.disable(); 
           }
           else{
              JOptionPane.showMessageDialog(null,"there is no account with this account number("+account_txt.getText()+")");

           }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_searchActionPerformed

    private void updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateActionPerformed
        // TODO add your handling code here:
        try{
            
            st=con.prepareStatement("Update open_account SET holder='"+holder_txt.getText()+"',type='"+type_combo.getSelectedItem().toString()+"',identity='"+identity_txt.getText()+"',contact='"+contact_txt.getText()+"',balance='"+balance_txt.getText()+"',status='"+status_combo.getSelectedItem().toString()+"' where account='"+account_txt.getText()+"'");
             int i=st.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null,"["+account_txt.getText()+"] has been updated");
            }
            else{
                JOptionPane.showMessageDialog(null,"could not update account due to some error");

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
        
    }//GEN-LAST:event_updateActionPerformed

    private void closeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeActionPerformed
        // TODO add your handling code here:
        try{
            String status= status_combo.getSelectedItem().toString();
            st=con.prepareStatement("Update open_account SET status='"+status+"' where account='"+account_txt.getText()+"'");
             int i=st.executeUpdate();
            if(i>0){
                JOptionPane.showMessageDialog(null,"["+account_txt.getText()+"] has been closed");
            }
            else{
                JOptionPane.showMessageDialog(null,"could not close account due to some error");

            }
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
    }//GEN-LAST:event_closeActionPerformed
public void clear_all_textboxes(){
                     account_txt.setText(null);
                     holder_txt.setText(null);
                     identity_txt.setText(null);
                     contact_txt.setText(null);
                     balance_txt.setText(null);
    
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField account_txt;
    private javax.swing.JTextField balance_txt;
    private javax.swing.JButton close;
    private javax.swing.JTextField contact_txt;
    private javax.swing.JButton create;
    private javax.swing.JTextField holder_txt;
    private javax.swing.JTextField identity_txt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton search;
    private javax.swing.JComboBox status_combo;
    private javax.swing.JComboBox type_combo;
    private javax.swing.JButton update;
    // End of variables declaration//GEN-END:variables

    private void setLocationRelativeTo(Object object) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
